import csv
from io import StringIO
from datetime import datetime
from typing import List, Dict, Any


def export_to_csv(
    data: List[Dict[str, Any]],
    report_title: str,
    generated_by: str,
    filters: Dict[str, Any] = None,
) -> StringIO:
    output = StringIO()
    writer = csv.writer(output)
    
    # Header section
    writer.writerow(["PeopleFlow HRMS"])
    writer.writerow([report_title])
    writer.writerow([])
    writer.writerow(["Generated By:", generated_by])
    writer.writerow(["Generated On:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")])
    
    if filters:
        writer.writerow([])
        writer.writerow(["Applied Filters:"])
        for key, value in filters.items():
            if value is not None:
                writer.writerow([f"  {key.replace('_', ' ').title()}:", value])
    
    writer.writerow([])
    
    # Data section
    if data:
        headers = list(data[0].keys())
        writer.writerow([h.replace('_', ' ').title() for h in headers])
        for row in data:
            writer.writerow([str(row.get(h, "")) for h in headers])
    
    output.seek(0)
    return output
