from datetime import datetime
from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill


def export_to_excel(
    data: list[dict[str, Any]],
    report_title: str,
    generated_by: str,
    filters: dict[str, Any] = None,
) -> BytesIO:
    output = BytesIO()
    wb = Workbook()
    ws = wb.active
    ws.title = report_title
    
    # Styles
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
    title_font = Font(bold=True, size=14)
    
    # Header section
    row_num = 1
    ws.cell(row=row_num, column=1, value="PeopleFlow HRMS").font = title_font
    row_num += 1
    ws.cell(row=row_num, column=1, value=report_title).font = title_font
    row_num += 2
    ws.cell(row=row_num, column=1, value="Generated By:")
    ws.cell(row=row_num, column=2, value=generated_by)
    row_num += 1
    ws.cell(row=row_num, column=1, value="Generated On:")
    ws.cell(row=row_num, column=2, value=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    row_num += 2
    
    if filters:
        ws.cell(row=row_num, column=1, value="Applied Filters:").font = Font(bold=True)
        row_num += 1
        for key, value in filters.items():
            if value is not None:
                ws.cell(row=row_num, column=1, value=f"  {key.replace('_', ' ').title()}:")
                ws.cell(row=row_num, column=2, value=str(value))
                row_num += 1
        row_num += 1
    
    # Data section
    if data:
        headers = list(data[0].keys())
        for col_num, header in enumerate(headers, 1):
            cell = ws.cell(row=row_num, column=col_num, value=header.replace('_', ' ').title())
            cell.font = header_font
            cell.fill = header_fill
        
        row_num += 1
        for row_data in data:
            for col_num, header in enumerate(headers, 1):
                ws.cell(row=row_num, column=col_num, value=str(row_data.get(header, "")))
            row_num += 1
    
    # Auto-adjust column widths
    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except (TypeError, ValueError):
                pass
        adjusted_width = min(max_length + 2, 50)
        ws.column_dimensions[column_letter].width = adjusted_width
    
    wb.save(output)
    output.seek(0)
    return output
