from io import BytesIO
from datetime import datetime
from typing import List, Dict, Any
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer
from reportlab.lib.units import inch


def export_to_pdf(
    data: List[Dict[str, Any]],
    report_title: str,
    generated_by: str,
    filters: Dict[str, Any] = None,
) -> BytesIO:
    output = BytesIO()
    doc = SimpleDocTemplate(output, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=12,
    )
    story.append(Paragraph("PeopleFlow HRMS", title_style))
    story.append(Paragraph(report_title, styles['Heading2']))
    story.append(Spacer(1, 12))
    
    # Metadata
    story.append(Paragraph(f"<b>Generated By:</b> {generated_by}", styles['Normal']))
    story.append(Paragraph(f"<b>Generated On:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 12))
    
    # Filters
    if filters:
        story.append(Paragraph("<b>Applied Filters:</b>", styles['Normal']))
        for key, value in filters.items():
            if value is not None:
                story.append(Paragraph(f"  • {key.replace('_', ' ').title()}: {value}", styles['Normal']))
        story.append(Spacer(1, 12))
    
    # Data table
    if data:
        headers = list(data[0].keys())
        table_data = [[h.replace('_', ' ').title() for h in headers]]
        
        for row_data in data:
            table_data.append([str(row_data.get(h, "")) for h in headers])
        
        table = Table(table_data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2563EB")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F3F4F6")),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#D1D5DB")),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        story.append(table)
    
    doc.build(story)
    output.seek(0)
    return output
