"""add_payroll_module

Revision ID: f396509f4b81
Revises: 6c1e8f2a9b40
Create Date: 2026-07-04 11:03:08.628824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f396509f4b81'
down_revision: Union[str, None] = '6c1e8f2a9b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=False),
    sa.Column('bonuses', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', name='payslipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_status'), 'payslips', ['status'], unique=False)
    op.create_index(op.f('ix_payslips_user_id'), 'payslips', ['user_id'], unique=False)
    op.add_column('employee_profiles', sa.Column('bonuses', sa.Float(), nullable=False))
    op.add_column('employee_profiles', sa.Column('tax', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'tax')
    op.drop_column('employee_profiles', 'bonuses')
    op.drop_index(op.f('ix_payslips_user_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_status'), table_name='payslips')
    op.drop_table('payslips')
    # ### end Alembic commands ###

